Extended netboot_info + replaced hardcoded url
archlinux/archweb pull request #400
Opened 2022-01-24 09:50 UTC by k4awon

This should resolve #364. Extended netboot_info to get ipxe package and pass along to netboot template.

2022-02-10 20:28 UTC, jelly requested changes

2022-02-20 07:56 UTC, k4awon commented on releng/views.py
> +    ipxepkg = Package.objects.get(pkgname='ipxe')
Thanks for the feedback. Added a try/except for error handling

2022-02-20 08:05 UTC, k4awon commented on releng/views.py
> +    ipxepkg = Package.objects.get(pkgname='ipxe')
Made a mistake here actually. Fixing this right now

2022-02-20 08:12 UTC, k4awon commented on releng/views.py
> +    ipxepkg = Package.objects.get(pkgname='ipxe')
Should be good now!

2022-02-23 20:50 UTC, jelly approved these changes
Thanks!

2022-02-23 20:51 UTC, merged