template: update outdated links on the download page
archlinux/archweb pull request #474
Opened 2023-08-08 16:15 UTC by christian-heusel

There are two outdated links on the download page:

- link to the releng/iso bugtracker
- link to the built vm images

fixes https://bugs.archlinux.org/task/79331
fixes https://bugs.archlinux.org/task/78321

2023-08-08 16:38 UTC, christian-heusel commented
The CI failure seems unrelated to me 🤔

2023-08-08 16:40 UTC, nl6720 requested changes

2023-08-08 16:45 UTC, christian-heusel commented on templates/public/download.html
> +                    title="Arch Linux Gitlab:Archiso">Bug Tracker</a></li>
applied in 1a8837e5a8b0cbe1fd6ba789670f6bf9b0bf76f3, thanks ✅

2023-08-08 16:51 UTC, nl6720 approved these changes

2023-08-10 08:51 UTC, jelly commented
Ugh Github does not rebase when testing... @christian-heusel pls rebase and tests will succeed :)

2023-08-10 08:56 UTC, christian-heusel commented
Rebased, tests now pass ✅

2023-08-10 09:33 UTC, jelly approved these changes

2023-08-10 09:33 UTC, merged

2023-08-10 09:33 UTC, jelly commented
Danke!